In [1]:
# INSTALL THE PACKAGES "PNADcIBGE" AND "expss"
install.packages("PNADcIBGE")
install.packages("expss")

# LOAD THE LIBRARIES
library(PNADcIBGE)
library(tidyverse)
library(expss)
library(survey)

variables = c("UF","V2001","V2005","V2007","V2009",
              "V2010","VD3004","VD4001","VD4002","VD4020",
              "VD4035", "VD4003", "VD4005", "VD4004A")

data = get_pnadc(year = 2024,
                 quarter = 4,
                 vars = variables)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘bitops’, ‘minqa’, ‘numDeriv’, ‘mitools’, ‘RcppArmadillo’, ‘projmgr’, ‘RCurl’, ‘survey’, ‘timeDate’


Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘checkmate’, ‘maditr’, ‘htmlTable’, ‘matrixStats’


── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Loading required package: maditr


To select columns from data: columns(mtcars, mpg, vs:carb)



Attaching package: ‘maditr’


The following objects are masked from ‘package:dplyr’:

    between, coalesce, first, last


The following object is masked from ‘package:purrr’:

    transpose


The following object is masked from ‘package:readr’:

    cols



Attaching package: ‘expss’


The following objects are masked from ‘package:stringr’:

    fixed, regex


The following objects are masked from ‘package:dplyr’:

    compute, contains, na_if, recode, vars, where


The following objects are masked from ‘package:purrr’:

    keep, modify, modify_if, when


The following objects are masked from ‘package:tidyr’:

    contains, nest


The following object is masked from ‘package:ggplot2’:

    vars


Loading required package: grid

Loading required package: Matrix


Attaching package: ‘Matrix’


The following objects are masked from ‘package:tidyr’:

    expand, pack, unpack


Loading required package: survival


Attaching package: ‘survey’


The following object is masked from ‘package:graphics’:

    dotchart

In [10]:
# CALCULATING THE TOTAL OF PEOPLE EMPLOYED AND UNEMPLOYED USING THE WEIGHTS CALCULATED BY "V1028" VARIABLE
indicators = data$variables %>%
 tab_cells(UF) %>%
 tab_cols(VD4002) %>%
 tab_weight(weight = V1028) %>%
 tab_stat_cases(total_statistic = "w_cases",
 total_label = "Total") %>%
 tab_pivot()

# TRANSFORMING THE DATA INTO A DATA FRAME AND RENAMING THE COLUMNS
indicators = as.data.frame(indicators)
colnames(indicators) = c("state", "people_employed", "people_unemployed")

# CREATING THE UNEMPLOYMENT RATE
indicators = indicators %>%
  mutate(unemployment_rate = people_unemployed/(people_employed+people_unemployed)*100)

# DELETING THE ROW WITH THE TOTAL
indicators = indicators[-c(28),]

# ADDING ACRONYM OF THE STATE AND REGION OF THE STATE
indicators$state = c("RO", "AC", "AM", "RR", "PA", "AP", "TO", "MA", "PI", "CE", "RN", "PB", "PE", "AL", "SE", "BA", "MG", "ES", "RJ", "SP", "PR", "SC", "RS", "MS", "MT", "GO", "DF")
indicators$region = c(rep("N", 7),rep("NE", 9), rep("SE", 4), rep("S", 3), rep("CO", 4))

# SELECTING THE COLUMNS
indicators = indicators %>%
  select(state, region, unemployment_rate)

indicators

   state region unemployment_rate
1  RO    N       2.763382
2  AC    N       7.281652
3  AM    N       8.320457
4  RR    N       6.605799
5  PA    N       7.164774
6  AP    N       8.718797
7  TO    N       5.058599
8  MA    NE      6.863770
9  PI    NE      7.530549
10 CE    NE      6.487631
11 RN    NE      8.546885
12 PB    NE      8.427995
13 PE    NE     10.195519
14 AL    NE      8.095677
15 SE    NE      8.447182
16 BA    NE      9.945569
17 MG    SE      4.282403
18 ES    SE      3.901851
19 RJ    SE      8.201856
20 SP    SE      5.923215
21 PR    S       3.251394
22 SC    S       2.670805
23 RS    S       4.530450
24 MS    CO      3.737735
25 MT    CO      2.464903
26 GO    CO      4.815546
27 DF    CO      9.067315